CREATE TABLE `EmailOutbox` (
  `id` VARCHAR(191) NOT NULL,
  `eventKey` VARCHAR(191) NOT NULL,
  `type` ENUM('PAYMENT_SUBMITTED', 'PAYMENT_APPROVED') NOT NULL,
  `toEmail` VARCHAR(320) NOT NULL,
  `toName` VARCHAR(191) NULL,
  `subject` VARCHAR(255) NOT NULL,
  `textBody` TEXT NOT NULL,
  `htmlBody` LONGTEXT NOT NULL,
  `status` ENUM('PENDING', 'PROCESSING', 'SENT', 'DEAD_LETTER') NOT NULL DEFAULT 'PENDING',
  `availableAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `attempts` INTEGER NOT NULL DEFAULT 0,
  `maxAttempts` INTEGER NOT NULL DEFAULT 5,
  `lockedBy` VARCHAR(191) NULL,
  `leaseExpiresAt` DATETIME(3) NULL,
  `heartbeatAt` DATETIME(3) NULL,
  `safeErrorCode` VARCHAR(191) NULL,
  `safeErrorMessage` TEXT NULL,
  `sentAt` DATETIME(3) NULL,
  `deadLetteredAt` DATETIME(3) NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,

  UNIQUE INDEX `EmailOutbox_eventKey_key`(`eventKey`),
  INDEX `EmailOutbox_status_availableAt_idx`(`status`, `availableAt`),
  INDEX `EmailOutbox_status_leaseExpiresAt_idx`(`status`, `leaseExpiresAt`),
  INDEX `EmailOutbox_type_createdAt_idx`(`type`, `createdAt`),
  PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
